Repository qbcore-framework/qb-inventory, pull requests merged in 2024-11, with the labels that each got.

#579 Fixed conflict with the names of some stashes.
  server/main.lua
Labels: question

#539 Make functions available for non-player inventories (stashes)
  server/functions.lua
Labels: enhancement

#517 fix: amount is nil in `GetTotalWeight` + misc lint issues
  client/drops.lua
  client/main.lua
  server/functions.lua
Labels: help wanted, invalid
